# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-08 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='章节名称')),
                ('bookname', models.CharField(max_length=150, verbose_name='书名')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('WordNumber', models.CharField(max_length=100, verbose_name='本章字数')),
                ('FaBuData', models.CharField(max_length=200, verbose_name='发布时间')),
                ('content', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '详情',
                'verbose_name_plural': '详情',
            },
        ),
        migrations.CreateModel(
            name='liebiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=200, verbose_name='书名')),
                ('img_url', models.TextField(verbose_name='图片链接')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('State', models.CharField(max_length=100, verbose_name='状态')),
                ('WordNumber', models.CharField(max_length=100, verbose_name='字数')),
                ('introduce', models.TextField(verbose_name='简介')),
            ],
            options={
                'verbose_name': '列表',
                'verbose_name_plural': '列表',
            },
        ),
        migrations.CreateModel(
            name='zhangjie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='章节名称')),
                ('zj_link', models.TextField(verbose_name='链接')),
                ('mf', models.CharField(max_length=100, verbose_name='状态')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
            },
        ),
        migrations.CreateModel(
            name='zonglei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='类别')),
                ('CGurl', models.TextField(verbose_name='类别链接')),
            ],
            options={
                'verbose_name': '总类别',
                'verbose_name_plural': '总类别',
            },
        ),
        migrations.AddField(
            model_name='liebiao',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_01.zonglei', verbose_name='类别'),
        ),
    ]
