# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-08 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liebiao',
            name='category',
            field=models.CharField(max_length=100, verbose_name='类别'),
        ),
    ]
