# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_01', '0004_auto_20190111_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='liebiao',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='zhangjie',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='zonglei',
            name='operator',
        ),
    ]
