# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-13 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_01', '0005_auto_20190111_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[(1, '普通用户'), (2, 'VIP'), (3, 'SVIP')], max_length=64, verbose_name='用户类型')),
                ('user', models.CharField(max_length=100, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=255, verbose_name='密码')),
            ],
            options={
                'verbose_name_plural': '用户',
                'verbose_name': '用户',
            },
        ),
    ]
