# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-05 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DianPu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店铺名称')),
            ],
            options={
                'verbose_name': '店铺名称',
                'verbose_name_plural': '店铺名称',
            },
        ),
        migrations.CreateModel(
            name='Dp_money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(verbose_name='经营资金')),
                ('dianpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.DianPu')),
            ],
        ),
        migrations.CreateModel(
            name='Dp_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100, verbose_name='经营项目')),
                ('dp_money', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Dp_money')),
            ],
        ),
        migrations.CreateModel(
            name='ShengFen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guo_jia', models.CharField(max_length=50, verbose_name='国家')),
                ('sheng_fen', models.CharField(max_length=100, verbose_name='省份')),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
            },
        ),
        migrations.CreateModel(
            name='XqDz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='详情地址')),
                ('shengfen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.ShengFen')),
            ],
            options={
                'verbose_name': '详情地址',
                'verbose_name_plural': '详情地址',
            },
        ),
        migrations.AddField(
            model_name='dianpu',
            name='xqdz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.XqDz'),
        ),
    ]
