# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-05 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dp_money',
            options={'verbose_name': '经营资金', 'verbose_name_plural': '经营资金'},
        ),
        migrations.AlterModelOptions(
            name='dp_project',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterField(
            model_name='dianpu',
            name='xqdz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.XqDz', verbose_name='详情地址'),
        ),
        migrations.AlterField(
            model_name='dp_money',
            name='dianpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.DianPu', verbose_name='店铺'),
        ),
        migrations.AlterField(
            model_name='dp_money',
            name='money',
            field=models.CharField(max_length=100, verbose_name='经营资金'),
        ),
        migrations.AlterField(
            model_name='dp_project',
            name='dp_money',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Dp_money', verbose_name='资金'),
        ),
        migrations.AlterField(
            model_name='xqdz',
            name='shengfen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.ShengFen', verbose_name='省份'),
        ),
    ]
